Análise de Filmes - https://www.imdb.com/pt/list/ls059930570/
* Dataset IMDb

In [50]:
# importar biblioteca pandas
import pandas as pd

# Ler o arquivo csv para o dataframe
df = pd.read_csv("https://raw.githubusercontent.com/marcosroquerosa/datasets/refs/heads/main/filmes_bilheteria/filmes_bilheteria.csv", sep=",")

In [51]:
# 5 primeiras linhas do df
df.head()

,Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
0,1,tt0499549,2014-02-24,2014-08-18,"WATCHED. $2,788.0",Avatar,Avatar,https://www.imdb.com/title/tt0499549/,Filme,7.9,162,2009,"Ação, Aventura, Fantasia, Ficção científica",1489938,2009-12-18,James Cameron
1,2,tt0120338,2014-02-24,2017-12-06,"WATCHED. $2,187.2",Titanic,Titanic,https://www.imdb.com/title/tt0120338/,Filme,8.0,194,1997,"Drama, Romance",1384874,1998-01-16,James Cameron
2,3,tt2488496,2015-12-24,2016-06-09,"WATCHED. $2,068.2",Star Wars: O Despertar da Força,Star Wars: Episode VII - The Force Awakens,https://www.imdb.com/title/tt2488496/,Filme,7.7,138,2015,"Ação, Aventura, Ficção científica",1021974,2015-12-17,J.J. Abrams
3,4,tt0369610,2015-06-23,2016-03-17,"WATCHED. $1,670.4",Jurassic World - O Mundo dos Dinossauros,Jurassic World,https://www.imdb.com/title/tt0369610/,Filme,6.9,124,2015,"Ação, Aventura, Ficção científica",726104,2015-06-11,Colin Trevorrow
4,5,tt0848228,2014-02-24,2016-01-04,"WATCHED. $1,519.6",Os Vingadores,The Avengers,https://www.imdb.com/title/tt0848228/,Filme,8.0,143,2012,"Ação, Ficção científica",1550681,2012-04-27,Joss Whedon

In [52]:
# 5 ultimos registros
df.tail()

,Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
713,714,tt1753383,2017-10-13,2017-10-13,WILL WATCH. $201.0,Quatro Vidas de um Cachorro,A Dog's Purpose,https://www.imdb.com/title/tt1753383/,Filme,7.3,100,2017,"Aventura, Comédia, Drama, Família, Fantasia",86004,2017-01-26,Lasse Hallström
714,715,tt0356634,2014-10-26,2014-10-26,WATCHED. $200.8,Garfield: O Filme,Garfield: The Movie,https://www.imdb.com/title/tt0356634/,Filme,5.1,80,2004,"Aventura, Comédia, Família, Fantasia",100399,2004-07-16,Peter Hewitt
715,716,tt0239395,2014-10-26,2014-10-26,WATCHED. $200.7,Como Cães e Gatos,Cats & Dogs,https://www.imdb.com/title/tt0239395/,Filme,5.2,87,2001,"Ação, Aventura, Comédia, Família, Fantasia",65476,2001-10-05,Lawrence Guterman
716,717,tt0099810,2014-10-26,2014-10-26,DIDN'T WATCH. $200.5,A Caçada ao Outubro Vermelho,The Hunt for Red October,https://www.imdb.com/title/tt0099810/,Filme,7.5,135,1990,"Ação, Aventura, Suspense",229986,1990-07-20,John McTiernan
717,718,tt0985699,2014-10-26,2014-10-26,DIDN'T WATCH. $200.3,Operação Valquíria,Valkyrie,https://www.imdb.com/title/tt0985699/,Filme,7.1,121,2008,"Drama, História, Suspense, Guerra",274074,2009-02-13,Bryan Singer

In [53]:
# numero de linhas e colunas
df.shape

(718, 16)

In [54]:
# Detalhe das colunas
df.columns

Index(['Position', 'Const', 'Created', 'Modified', 'Description', 'Title',
       'Original Title', 'URL', 'Title Type', 'IMDb Rating', 'Runtime (mins)',
       'Year', 'Genres', 'Num Votes', 'Release Date', 'Directors'],
      dtype='object')

In [55]:
# Visualiza os tipos de dados que o pandas identificou
df.dtypes

Position            int64
Const              object
Created            object
Modified           object
Description        object
Title              object
Original Title     object
URL                object
Title Type         object
IMDb Rating       float64
Runtime (mins)      int64
Year                int64
Genres             object
Num Votes           int64
Release Date       object
Directors          object
dtype: object

In [56]:
# Mostra informações gerais do df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 718 entries, 0 to 717
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Position        718 non-null    int64
 1   Const           718 non-null    object
 2   Created         718 non-null    object
 3   Modified        718 non-null    object
 4   Description     718 non-null    object
 5   Title           718 non-null    object
 6   Original Title  718 non-null    object
 7   URL             718 non-null    object
 8   Title Type      718 non-null    object
 9   IMDb Rating     718 non-null    float64
 10  Runtime (mins)  718 non-null    int64
 11  Year            718 non-null    int64
 12  Genres          718 non-null    object
 13  Num Votes       718 non-null    int64
 14  Release Date    718 non-null    object
 15  Directors       718 non-null    object
dtypes: float64(1), int64(4), object(11)
memory usage: 89.9+ KB

In [57]:
# Analise estatísticas: contagem, media, desvio padrão, min, max e porcentagens.
df.describe()

         Position  IMDb Rating  Runtime (mins)         Year     Num Votes
count  718.000000   718.000000      718.000000   718.000000  7.180000e+02
mean   359.500000     6.887047      117.750696  2005.568245  4.617833e+05
std    207.413034     0.894668       22.210367     9.810773  4.132260e+05
min      1.000000     3.500000       69.000000  1939.000000  2.024000e+03
25%    180.250000     6.300000      101.000000  2000.000000  2.047670e+05
50%    359.500000     6.900000      116.000000  2008.000000  3.318310e+05
75%    538.750000     7.500000      130.000000  2013.000000  5.754232e+05
max    718.000000     9.200000      238.000000  2017.000000  3.146742e+06

In [58]:
# Seleção de dados - restringir colunas - nome exato da coluna.
df[['Title', 'Year', 'IMDb Rating']]

                                        Title  Year  IMDb Rating
0                                      Avatar  2009          7.9
1                                     Titanic  1997          8.0
2             Star Wars: O Despertar da Força  2015          7.7
3    Jurassic World - O Mundo dos Dinossauros  2015          6.9
4                               Os Vingadores  2012          8.0
..                                        ...   ...          ...
713               Quatro Vidas de um Cachorro  2017          7.3
714                         Garfield: O Filme  2004          5.1
715                         Como Cães e Gatos  2001          5.2
716              A Caçada ao Outubro Vermelho  1990          7.5
717                        Operação Valquíria  2008          7.1

[718 rows x 3 columns]

In [59]:
#Filtragem - Filmes lançados a partir de 2010
df[df['Year'] > 2010]
# Filtragem por ordem crescente
df[df['Year'] > 2010].sort_values(by="Year", ascending=True)

,Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
22,23,tt1298650,2014-02-24,2014-02-24,"WATCHED. $1,045.7",Piratas do Caribe: Navegando em Águas Misteriosas,Pirates of the Caribbean: On Stranger Tides,https://www.imdb.com/title/tt1298650/,Filme,6.6,137,2011,"Ação, Aventura, Fantasia",604472,2011-05-20,Rob Marshall
642,643,tt1284575,2014-10-26,2014-10-26,DIDN'T WATCH. $216.2,Professora Sem Classe,Bad Teacher,https://www.imdb.com/title/tt1284575/,Filme,5.7,92,2011,"Comédia, Romance",222325,2011-08-19,Jake Kasdan
650,651,tt1564367,2014-10-26,2014-10-26,DIDN'T WATCH. $214.9,Esposa de Mentirinha,Just Go with It,https://www.imdb.com/title/tt1564367/,Filme,6.4,117,2011,"Comédia, Romance",288317,2011-03-04,Dennis Dugan
625,626,tt1133985,2014-10-26,2014-10-26,WATCHED. $219.9,Lanterna Verde,Green Lantern,https://www.imdb.com/title/tt1133985/,Filme,5.5,114,2011,"Ação, Aventura, Ficção científica",307902,2011-08-19,Martin Campbell
639,640,tt1454029,2014-10-26,2014-10-26,WATCHED. $216.6,Histórias Cruzadas,The Help,https://www.imdb.com/title/tt1454029/,Filme,8.1,146,2011,Drama,526549,2012-02-03,Tate Taylor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,616,tt2239822,2017-09-07,2017-09-28,WILL WATCH. $223.2,Valerian e a Cidade dos Mil Planetas,Valerian and the City of a Thousand Planets,https://www.imdb.com/title/tt2239822/,Filme,6.4,136,2017,"Animação, Ação, Aventura, Fantasia, Ficção cie...",208808,2017-08-10,Luc Besson
69,70,tt1790809,2017-06-30,2017-10-25,"WATCHED. $794.8still ongoing, not yet final",Piratas do Caribe: A Vingança de Salazar,Pirates of the Caribbean: Dead Men Tell No Tales,https://www.imdb.com/title/tt1790809/,Filme,6.5,129,2017,"Ação, Aventura, Fantasia",382706,2017-05-25,"Joachim Rønning, Espen Sandberg"
62,63,tt0451279,2017-07-10,2017-11-20,WATCHED. $821.8,Mulher-Maravilha,Wonder Woman,https://www.imdb.com/title/tt0451279/,Filme,7.3,141,2017,"Ação, Aventura, Fantasia, Ficção científica, G...",733468,2017-06-01,Patty Jenkins
23,24,tt3469046,2017-07-25,2017-12-06,"WILL WATCH. $1,032.2still ongoing, not yet final",Meu Malvado Favorito 3,Despicable Me 3,https://www.imdb.com/title/tt3469046/,Filme,6.3,89,2017,"Animação, Aventura, Comédia, Policial, Família...",179225,2017-06-29,"Kyle Balda, Pierre Coffin, Eric Guillon"
713,714,tt1753383,2017-10-13,2017-10-13,WILL WATCH. $201.0,Quatro Vidas de um Cachorro,A Dog's Purpose,https://www.imdb.com/title/tt1753383/,Filme,7.3,100,2017,"Aventura, Comédia, Drama, Família, Fantasia",86004,2017-01-26,Lasse Hallström

In [60]:
# Filtrar filmes lançados a partir de 2010 e com nota acima de 7 (0 a 10)
df[(df['Year'] > 2010) &
    (df['IMDb Rating'] > 7)]

,Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
2,3,tt2488496,2015-12-24,2016-06-09,"WATCHED. $2,068.2",Star Wars: O Despertar da Força,Star Wars: Episode VII - The Force Awakens,https://www.imdb.com/title/tt2488496/,Filme,7.7,138,2015,"Ação, Aventura, Ficção científica",1021974,2015-12-17,J.J. Abrams
4,5,tt0848228,2014-02-24,2016-01-04,"WATCHED. $1,519.6",Os Vingadores,The Avengers,https://www.imdb.com/title/tt0848228/,Filme,8.0,143,2012,"Ação, Ficção científica",1550681,2012-04-27,Joss Whedon
5,6,tt2820852,2015-04-13,2016-03-17,"NOT YET WATCHED. $1,516.0",Velozes & Furiosos 7,Fast & Furious 7,https://www.imdb.com/title/tt2820852/,Filme,7.1,137,2015,"Ação, Suspense",438112,2015-04-02,James Wan
6,7,tt2395427,2015-05-03,2016-03-17,"WATCHED. $1,405.4",Vingadores: Era de Ultron,Avengers: Age of Ultron,https://www.imdb.com/title/tt2395427/,Filme,7.3,141,2015,"Ação, Aventura, Ficção científica",994598,2015-04-23,Joss Whedon
7,8,tt1201607,2014-02-24,2014-02-24,"WATCHED. $1,341.5",Harry Potter e as Relíquias da Morte: Parte 2,Harry Potter and the Deathly Hallows: Part 2,https://www.imdb.com/title/tt1201607/,Filme,8.1,130,2011,"Aventura, Família, Fantasia, Mistério",1039360,2011-07-15,David Yates
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,tt2719848,2015-11-25,2016-03-17,WILL WATCH. $203.4,Evereste,Everest,https://www.imdb.com/title/tt2719848/,Filme,7.1,121,2015,"Aventura, Biografia, Drama, Suspense",246293,2015-09-24,Baltasar Kormákur
705,706,tt2543164,2017-06-10,2017-06-10,WATCHED. $202.1,A Chegada,Arrival,https://www.imdb.com/title/tt2543164/,Filme,7.9,116,2016,"Drama, Mistério, Ficção científica",856574,2016-11-24,Denis Villeneuve
710,711,tt1398426,2015-11-13,2016-01-31,DIDN'T WATCH. $201.6,Straight Outta Compton: A História do N.W.A.,Straight Outta Compton,https://www.imdb.com/title/tt1398426/,Filme,7.8,147,2015,"Biografia, Drama, História, Musical, Musical",232988,2015-10-29,F. Gary Gray
711,712,tt1232829,2014-10-26,2014-10-26,WATCHED. $201.6,Anjos da Lei,21 Jump Street,https://www.imdb.com/title/tt1232829/,Filme,7.2,109,2012,"Ação, Comédia, Policial",642848,2012-05-04,"Phil Lord, Christopher Miller"
713,714,tt1753383,2017-10-13,2017-10-13,WILL WATCH. $201.0,Quatro Vidas de um Cachorro,A Dog's Purpose,https://www.imdb.com/title/tt1753383/,Filme,7.3,100,2017,"Aventura, Comédia, Drama, Família, Fantasia",86004,2017-01-26,Lasse Hallström

In [61]:
# Filtrar filmes que tem ação.
df_filmes_de_acao = df[df['Genres'].str.contains("Ação")]

In [62]:
df_filmes_de_acao.size

5520

In [63]:
df.dtypes

Position            int64
Const              object
Created            object
Modified           object
Description        object
Title              object
Original Title     object
URL                object
Title Type         object
IMDb Rating       float64
Runtime (mins)      int64
Year                int64
Genres             object
Num Votes           int64
Release Date       object
Directors          object
dtype: object

In [64]:
# Tratar Datas
# (Provavelmente tem espações em branco e formato de data diferente, o mixed resolve mas pode converter errado)
# df['Release Date'] = pd.to_datetime(df['Release Date'], format="mixed")
# df['Created'] = pd.to_datetime(df['Created'], format="mixed")
# df['Modified'] = pd.to_datetime(df['Modified'], format="mixed")

In [65]:
# 1. Limpeza básica Release Date
df["Release Date"] = df["Release Date"].astype(str).str.strip()

# 2. Conversão segura
df["Release Date"] = pd.to_datetime(df["Release Date"], errors="coerce")

# 3. Diagnóstico
erros = df[df["Release Date"].isnull()]

print("Linhas com erro:", len(erros))
erros.head()

Linhas com erro: 1

,Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
709,710,tt0876563,2014-10-26,2014-10-26,WATCHED. $201.8,Ponyo: Uma Amizade que Veio do Mar,Gake no ue no Ponyo,https://www.imdb.com/title/tt0876563/,Filme,7.6,101,2008,"Animação, Aventura, Comédia, Família, Fantasia",183898,NaT,Hayao Miyazaki

In [66]:
# 1. Limpeza básica Created
df["Created"] = df["Created"].astype(str).str.strip()

# 2. Conversão segura
df["Created"] = pd.to_datetime(df["Created"], errors="coerce")

# 3. Diagnóstico
erros = df[df["Created"].isnull()]

print("Linhas com erro:", len(erros))
erros.head()

Linhas com erro: 0

Empty DataFrame
Columns: [Position, Const, Created, Modified, Description, Title, Original Title, URL, Title Type, IMDb Rating, Runtime (mins), Year, Genres, Num Votes, Release Date, Directors]
Index: []

In [67]:
# 1. Limpeza básica Modified
df["Modified"] = df["Modified"].astype(str).str.strip()

# 2. Conversão segura
df["Modified"] = pd.to_datetime(df["Modified"], errors="coerce")

# 3. Diagnóstico
erros = df[df["Modified"].isnull()]

print("Linhas com erro:", len(erros))
erros.head()

Linhas com erro: 0

Empty DataFrame
Columns: [Position, Const, Created, Modified, Description, Title, Original Title, URL, Title Type, IMDb Rating, Runtime (mins), Year, Genres, Num Votes, Release Date, Directors]
Index: []

In [68]:
df.head()

,Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
0,1,tt0499549,2014-02-24,2014-08-18,"WATCHED. $2,788.0",Avatar,Avatar,https://www.imdb.com/title/tt0499549/,Filme,7.9,162,2009,"Ação, Aventura, Fantasia, Ficção científica",1489938,2009-12-18,James Cameron
1,2,tt0120338,2014-02-24,2017-12-06,"WATCHED. $2,187.2",Titanic,Titanic,https://www.imdb.com/title/tt0120338/,Filme,8.0,194,1997,"Drama, Romance",1384874,1998-01-16,James Cameron
2,3,tt2488496,2015-12-24,2016-06-09,"WATCHED. $2,068.2",Star Wars: O Despertar da Força,Star Wars: Episode VII - The Force Awakens,https://www.imdb.com/title/tt2488496/,Filme,7.7,138,2015,"Ação, Aventura, Ficção científica",1021974,2015-12-17,J.J. Abrams
3,4,tt0369610,2015-06-23,2016-03-17,"WATCHED. $1,670.4",Jurassic World - O Mundo dos Dinossauros,Jurassic World,https://www.imdb.com/title/tt0369610/,Filme,6.9,124,2015,"Ação, Aventura, Ficção científica",726104,2015-06-11,Colin Trevorrow
4,5,tt0848228,2014-02-24,2016-01-04,"WATCHED. $1,519.6",Os Vingadores,The Avengers,https://www.imdb.com/title/tt0848228/,Filme,8.0,143,2012,"Ação, Ficção científica",1550681,2012-04-27,Joss Whedon

In [69]:
df["Bilheteria"] = (
    df["Description"]
    .str.extract(r"\$([\d,]+\.?\d*)")
    .replace(",", "", regex=True)
    .astype(float)
)

In [70]:
df['Bilheteria']

0      2788.0
1      2187.2
2      2068.2
3      1670.4
4      1519.6
        ...
713     201.0
714     200.8
715     200.7
716     200.5
717     200.3
Name: Bilheteria, Length: 718, dtype: float64

In [71]:
df.isnull().sum()

Position          0
Const             0
Created           0
Modified          0
Description       0
Title             0
Original Title    0
URL               0
Title Type        0
IMDb Rating       0
Runtime (mins)    0
Year              0
Genres            0
Num Votes         0
Release Date      1
Directors         0
Bilheteria        0
dtype: int64

In [72]:
df.dropna(subset=["IMDb Rating"])

#df["Bilheteria"].fillna(df["Bilheteria"].mean(), inplace=True)
#df["Bilheteria"] = df["Bilheteria"].fillna(df["Bilheteria"].mean())

,Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Bilheteria
0,1,tt0499549,2014-02-24,2014-08-18,"WATCHED. $2,788.0",Avatar,Avatar,https://www.imdb.com/title/tt0499549/,Filme,7.9,162,2009,"Ação, Aventura, Fantasia, Ficção científica",1489938,2009-12-18,James Cameron,2788.0
1,2,tt0120338,2014-02-24,2017-12-06,"WATCHED. $2,187.2",Titanic,Titanic,https://www.imdb.com/title/tt0120338/,Filme,8.0,194,1997,"Drama, Romance",1384874,1998-01-16,James Cameron,2187.2
2,3,tt2488496,2015-12-24,2016-06-09,"WATCHED. $2,068.2",Star Wars: O Despertar da Força,Star Wars: Episode VII - The Force Awakens,https://www.imdb.com/title/tt2488496/,Filme,7.7,138,2015,"Ação, Aventura, Ficção científica",1021974,2015-12-17,J.J. Abrams,2068.2
3,4,tt0369610,2015-06-23,2016-03-17,"WATCHED. $1,670.4",Jurassic World - O Mundo dos Dinossauros,Jurassic World,https://www.imdb.com/title/tt0369610/,Filme,6.9,124,2015,"Ação, Aventura, Ficção científica",726104,2015-06-11,Colin Trevorrow,1670.4
4,5,tt0848228,2014-02-24,2016-01-04,"WATCHED. $1,519.6",Os Vingadores,The Avengers,https://www.imdb.com/title/tt0848228/,Filme,8.0,143,2012,"Ação, Ficção científica",1550681,2012-04-27,Joss Whedon,1519.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
713,714,tt1753383,2017-10-13,2017-10-13,WILL WATCH. $201.0,Quatro Vidas de um Cachorro,A Dog's Purpose,https://www.imdb.com/title/tt1753383/,Filme,7.3,100,2017,"Aventura, Comédia, Drama, Família, Fantasia",86004,2017-01-26,Lasse Hallström,201.0
714,715,tt0356634,2014-10-26,2014-10-26,WATCHED. $200.8,Garfield: O Filme,Garfield: The Movie,https://www.imdb.com/title/tt0356634/,Filme,5.1,80,2004,"Aventura, Comédia, Família, Fantasia",100399,2004-07-16,Peter Hewitt,200.8
715,716,tt0239395,2014-10-26,2014-10-26,WATCHED. $200.7,Como Cães e Gatos,Cats & Dogs,https://www.imdb.com/title/tt0239395/,Filme,5.2,87,2001,"Ação, Aventura, Comédia, Família, Fantasia",65476,2001-10-05,Lawrence Guterman,200.7
716,717,tt0099810,2014-10-26,2014-10-26,DIDN'T WATCH. $200.5,A Caçada ao Outubro Vermelho,The Hunt for Red October,https://www.imdb.com/title/tt0099810/,Filme,7.5,135,1990,"Ação, Aventura, Suspense",229986,1990-07-20,John McTiernan,200.5
717,718,tt0985699,2014-10-26,2014-10-26,DIDN'T WATCH. $200.3,Operação Valquíria,Valkyrie,https://www.imdb.com/title/tt0985699/,Filme,7.1,121,2008,"Drama, História, Suspense, Guerra",274074,2009-02-13,Bryan Singer,200.3

In [73]:
# Remover duplicatas
df.drop_duplicates(inplace=True)

In [74]:
# Manipulação de Colunas
# Criar novas métricas
df["Bilheteria_por_minuto"] = df["Bilheteria"] / df["Runtime (mins)"]

In [75]:
#Extrair ano da data
df["Ano_Lancamento"] = df["Release Date"].dt.year

In [77]:
# Ordenação
df.sort_values("Bilheteria", ascending=False)
df.sort_values("IMDb Rating", ascending=False)

,Position,Const,Created,Modified,Description,Title,Original Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Bilheteria,Bilheteria_por_minuto,Ano_Lancamento
543,544,tt0068646,2014-10-26,2014-10-26,DIDN'T WATCH. $245.1,O Poderoso Chefão,The Godfather,https://www.imdb.com/title/tt0068646/,Filme,9.2,175,1972,"Policial, Drama",2213698,1972-09-10,Francis Ford Coppola,245.1,1.400571,1972.0
30,31,tt0468569,2014-02-24,2014-02-24,"WATCHED. $1,004.6",Batman: O Cavaleiro das Trevas,The Dark Knight,https://www.imdb.com/title/tt0468569/,Filme,9.1,152,2008,"Ação, Policial, Drama, Suspense",3146742,2008-07-18,Christopher Nolan,1004.6,6.609211,2008.0
377,378,tt0108052,2014-10-13,2014-10-13,WATCHED. $321.3,A Lista de Schindler,Schindler's List,https://www.imdb.com/title/tt0108052/,Filme,9.0,195,1993,"Biografia, Drama, História",1577956,1994-03-11,Steven Spielberg,321.3,1.647692,1994.0
15,16,tt0167260,2014-02-24,2014-02-24,"WATCHED. $1,119.9",O Senhor dos Anéis: O Retorno do Rei,The Lord of the Rings: The Return of the King,https://www.imdb.com/title/tt0167260/,Filme,9.0,201,2003,"Aventura, Drama, Fantasia",2152744,2003-12-25,Peter Jackson,1119.9,5.571642,2003.0
53,54,tt0120737,2014-02-24,2014-02-24,WATCHED. $871.5,O Senhor dos Anéis: A Sociedade do Anel,The Lord of the Rings: The Fellowship of the Ring,https://www.imdb.com/title/tt0120737/,Filme,8.9,178,2001,"Aventura, Drama, Fantasia",2194161,2002-01-01,Peter Jackson,871.5,4.896067,2002.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,344,tt1615918,2014-10-13,2014-10-13,WATCHED. $342.7,Alvin e os Esquilos 3,Alvin and the Chipmunks: Chipwrecked,https://www.imdb.com/title/tt1615918/,Filme,4.4,87,2011,"Animação, Aventura, Comédia, Família, Fantasia...",44326,2012-01-06,Mike Mitchell,342.7,3.939080,2012.0
143,144,tt2322441,2015-02-23,2016-03-17,WATCHED. $571.0,Cinquenta Tons de Cinza,Fifty Shades of Grey,https://www.imdb.com/title/tt2322441/,Filme,4.2,125,2015,"Drama, Romance, Suspense",354929,2015-02-12,Sam Taylor-Johnson,571.0,4.568000,2015.0
381,382,tt0938283,2014-10-13,2014-10-13,DIDN'T WATCH. $319.7,O Último Mestre do Ar,The Last Airbender,https://www.imdb.com/title/tt0938283/,Filme,3.9,103,2010,"Ação, Aventura, Família, Fantasia",180789,2010-08-20,M. Night Shyamalan,319.7,3.103883,2010.0
566,567,tt0118688,2014-10-26,2014-10-26,WATCHED. $238.2,Batman & Robin,Batman & Robin,https://www.imdb.com/title/tt0118688/,Filme,3.8,125,1997,"Ação, Ficção científica",281593,1997-07-04,Joel Schumacher,238.2,1.905600,1997.0
636,637,tt4877122,2017-10-25,2017-12-06,"DIDN'T WATCH. $216.9still ongoing, not yet final",Emoji: O Filme,The Emoji Movie,https://www.imdb.com/title/tt4877122/,Filme,3.5,86,2017,"Animação, Aventura, Comédia, Família, Fantasia...",79138,2017-08-31,Tony Leondis,216.9,2.522093,2017.0

In [78]:
# Agrupamento (GroupBy)
# Bilheteria média por ano
df.groupby("Year")["Bilheteria"].mean()

Year
1939    400.200000
1942    267.400000
1961    215.900000
1967    205.800000
1972    245.100000
1973    441.300000
1975    470.700000
1977    439.800000
1978    347.600000
1979    210.300000
1980    538.400000
1981    389.900000
1982    792.900000
1983    475.100000
1984    314.900000
1985    302.375000
1986    342.500000
1987    278.033333
1988    285.920000
1989    291.966667
1990    312.872727
1991    352.566667
1992    322.911111
1993    376.333333
1994    369.116667
1995    303.753846
1996    359.375000
1997    420.488235
1998    314.817647
1999    369.335000
2000    301.076190
2001    388.609524
2002    418.285000
2003    406.347619
2004    387.815385
2005    440.000000
2006    431.400000
2007    446.844000
2008    377.805714
2009    511.920000
2010    417.242105
2011    458.250000
2012    497.383784
2013    464.132500
2014    448.234091
2015    555.645946
2016    477.052174
2017    514.511111
Name: Bilheteria, dtype: float64

In [80]:
# Número de filmes por diretor
df.groupby("Directors")["Title"].count()

Directors
Aaron Blaise, Robert Walker    1
Adam Shankman                  2
Adrian Lyne                    2
Alan J. Pakula                 1
Alan Taylor                    2
                              ..
Wolfgang Reitherman            1
Wuershan                       1
Yimou Zhang                    1
Zack Snyder                    4
Zheng Xu                       1
Name: Title, Length: 391, dtype: int64

In [81]:
ranking = (
    df.groupby("Directors")
    .agg(
        total_filmes=("Title", "count"),
        filmes=("Title", lambda x: list(x))
    )
    .sort_values("total_filmes", ascending=False)
)

ranking.head()

,total_filmes,filmes
Directors,,
Steven Spielberg,19,"[Jurassic Park: O Parque dos Dinossauros, E.T...."
Robert Zemeckis,9,"[Forrest Gump: O Contador de Histórias, Náufra..."
Ridley Scott,9,"[Perdido em Marte, Gladiador, Prometheus, Hann..."
Michael Bay,9,"[Transformers: O Lado Oculto da Lua, Transform..."
Roland Emmerich,8,"[Independence Day, 2012, O Dia Depois de Amanh..."

In [82]:
# Múltiplas métricas

df.groupby("Year").agg({
    "Bilheteria": ["sum", "mean"],
    "IMDb Rating": "mean"
})

     Bilheteria             IMDb Rating
            sum        mean        mean
Year
1939      400.2  400.200000    8.200000
1942      267.4  267.400000    7.300000
1961      215.9  215.900000    7.300000
1967      205.8  205.800000    7.600000
1972      245.1  245.100000    9.200000
1973      441.3  441.300000    8.100000
1975      470.7  470.700000    8.100000
1977     1319.4  439.800000    7.666667
1978      695.2  347.600000    7.300000
1979      210.3  210.300000    6.300000
1980      538.4  538.400000    8.700000
1981      389.9  389.900000    8.400000
1982      792.9  792.900000    7.900000
1983      475.1  475.100000    8.300000
1984      944.7  314.900000    7.566667
1985     1209.5  302.375000    7.275000
1986      685.0  342.500000    6.850000
1987      834.1  278.033333    6.866667
1988     1429.6  285.920000    6.940000
1989     2627.7  291.966667    7.277778
1990     3441.6  312.872727    7.245455
1991     2115.4  352.566667    7.816667
1992     2906.2  322.911111    7.100000
1993     3387.0  376.333333    7.333333
1994     4429.4  369.116667    7.316667
1995     3948.8  303.753846    7.138462
1996     4312.5  359.375000    6.733333
1997     7148.3  420.488235    7.029412
1998     5351.9  314.817647    6.964706
1999     7386.7  369.335000    6.940000
2000     6322.6  301.076190    6.880952
2001     8160.8  388.609524    7.038095
2002     8365.7  418.285000    7.035000
2003     8533.3  406.347619    6.885714
2004    10083.2  387.815385    7.007692
2005     7920.0  440.000000    6.811111
2006     8628.0  431.400000    6.910000
2007    11171.1  446.844000    6.728000
2008    13223.2  377.805714    6.717143
2009    15357.6  511.920000    6.773333
2010    15855.2  417.242105    6.547368
2011    15580.5  458.250000    6.711765
2012    18403.2  497.383784    6.921622
2013    18565.3  464.132500    6.740000
2014    19722.3  448.234091    6.865909
2015    20558.9  555.645946    6.656757
2016    21944.4  477.052174    6.850000
2017    18522.4  514.511111    6.602778

In [83]:
# Tabela Dinâmica
# Bilheteria por ano

pd.pivot_table(
    df,
    values="Bilheteria",
    index="Year",
    aggfunc="sum"
)

      Bilheteria
Year
1939       400.2
1942       267.4
1961       215.9
1967       205.8
1972       245.1
1973       441.3
1975       470.7
1977      1319.4
1978       695.2
1979       210.3
1980       538.4
1981       389.9
1982       792.9
1983       475.1
1984       944.7
1985      1209.5
1986       685.0
1987       834.1
1988      1429.6
1989      2627.7
1990      3441.6
1991      2115.4
1992      2906.2
1993      3387.0
1994      4429.4
1995      3948.8
1996      4312.5
1997      7148.3
1998      5351.9
1999      7386.7
2000      6322.6
2001      8160.8
2002      8365.7
2003      8533.3
2004     10083.2
2005      7920.0
2006      8628.0
2007     11171.1
2008     13223.2
2009     15357.6
2010     15855.2
2011     15580.5
2012     18403.2
2013     18565.3
2014     19722.3
2015     20558.9
2016     21944.4
2017     18522.4

In [85]:
# Nota média por gênero (cuidado: múltiplos gêneros)
# Explodir gêneros:
df_exploded = df.assign(Genre=df["Genres"].str.split(", ")).explode("Genre")

pd.pivot_table(
    df_exploded,
    values="IMDb Rating",
    index="Genre",
    aggfunc="mean"
).sort_values(by="IMDb Rating", ascending=False)

                   IMDb Rating
Genre
Biografia             7.669231
Guerra                7.463636
História              7.382353
Documentário          7.350000
Drama                 7.196581
Faroeste              7.160000
Mistério              7.080556
Policial              6.958163
Animação              6.955285
Esportes              6.940000
Ficção científica     6.824468
Aventura              6.800519
Suspense              6.782524
Família               6.774457
Terror                6.763636
Ação                  6.756522
Musical               6.740678
Romance               6.736975
Fantasia              6.718269
Comédia               6.677032

In [86]:
# Strings
df["Title"].str.upper()
df["Genres"].str.split(", ")
df["Title"].str.contains("Star")

0      False
1      False
2       True
3      False
4      False
       ...
713    False
714    False
715    False
716    False
717    False
Name: Title, Length: 718, dtype: bool

In [89]:
# Datas
df["Release Date"].dt.year
df["Release Date"].dt.month
df["Release Date"].dt.day_name()

0        Friday
1        Friday
2      Thursday
3      Thursday
4        Friday
         ...
713    Thursday
714      Friday
715      Friday
716      Friday
717      Friday
Name: Release Date, Length: 718, dtype: object

In [90]:
# Estatísticas
df["Bilheteria"].mean()
df["Bilheteria"].sum()
df["IMDb Rating"].std()

df[["Bilheteria", "IMDb Rating"]].corr()

             Bilheteria  IMDb Rating
Bilheteria     1.000000     0.234513
IMDb Rating    0.234513     1.000000

In [96]:
# Correlação considerando DURAÇÃO
#| Valor       | Força (regra prática) |
#| ----------- | --------------------- |
#| 0.00 – 0.19 | Muito fraca           |
#| 0.20 – 0.39 | Fraca                 |
#| 0.40 – 0.59 | Moderada              |
#| 0.60 – 0.79 | Forte                 |
#| 0.80 – 1.00 | Muito forte           |


df[["Bilheteria", "IMDb Rating", "Runtime (mins)"]].corr()

                Bilheteria  IMDb Rating  Runtime (mins)
Bilheteria        1.000000     0.234513        0.268492
IMDb Rating       0.234513     1.000000        0.356582
Runtime (mins)    0.268492     0.356582        1.000000

In [97]:
# Exportação
df.to_csv("filmes_tratados.csv", index=False)
df.to_excel("filmes_tratados.xlsx", index=False)