# Beautiful Soup é uma biblioteca em Python utilizada para extrair informações de páginas HTML ou XML.
Vamos acessar a página de notícias do IFPR: url = https://ifpr.edu.br/foz-do-iguacu/

In [ ]:
# Antes de começar, instale as bibliotecas necessárias.
!pip install beautifulsoup4
!pip install requests
!pip install pandas

In [3]:
# Importando as bibliotecas
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [8]:
# Fazendo download de uma página
#Vamos acessar a página de notícias do IFPR.
url = "https://ifpr.edu.br/foz-do-iguacu/"
resposta = requests.get(url)
html = resposta.text

In [9]:
#Criando o objeto BeautifulSoup
# Agora vamos transformar o HTML em um objeto analisável.
soup = BeautifulSoup(html, "html.parser")

In [ ]:
#Visualizando o HTML formatado
print(soup.prettify())

In [11]:
# Encontrando elementos HTML
#O método find() retorna o primeiro elemento encontrado.
titulo = soup.find("h1")
print(titulo.text)

Projeto IFPR Maker ofertará oficinas de programação e robótica para estudantes de escolas públicas

In [12]:
# O método find_all() retorna uma lista de elementos.
titulos = soup.find_all("h2")

for t in titulos:
    print(t.text)

IFPR Foz realiza programação especial alusiva ao Mês das Mulheres
Jogos Internos 2026 do IFPR Foz celebram o esporte e a integração
Cineciência promove reflexão sobre o papel das mulheres na ciência em evento no IFPR Foz
IFPR abre inscrições para projeto de orientação a estudos no exterior
Páginas dos Campi
Nossos Cursos
Nossos Campi
Fale Conosco
Redes Sociais
Privacidade
Sistema e-mec

In [13]:
#Buscando por classe CSS
#Muitos sites organizam notícias por classes CSS

noticias = soup.find_all("div", class_="row noticias-complementares")

for noticia in noticias:
    print(noticia.text)

Notícias

IFPR Foz realiza programação especial alusiva ao Mês das Mulheres
Como você tem contribuído para a igualdade de gênero? Para refletir sobre essa questão tão importante, o Instituto Federal do Paraná…



Esportes

Jogos Internos 2026 do IFPR Foz celebram o esporte e a integração
Dois dias de muita competição, integração e espírito esportivo marcaram os Jogos Internos do IFPR – Campus Foz do Iguaçu. Realizado…



Notícias

Cineciência promove reflexão sobre o papel das mulheres na ciência em evento no IFPR Foz
Você já parou para pensar nos desafios enfrentados pelas mulheres que transformaram a história da ciência? Pensando em dar visibilidade a…



Internacional

IFPR abre inscrições para projeto de orientação a estudos no exterior
O Instituto Federal do Paraná (IFPR) – Campus Foz do Iguaçu está com inscrições abertas para o Projeto de Extensão  “International…





Notícias

 IFPR Foz recebe professor visitante da República Dominicana
 Publicados editais de Afastamento Integral para Pós Graduação
 IFPR Foz celebra Formatura 2026
 Divulgado resultado da prova de Suficiência em Inglês – 2026
 Abertas as inscrições para estágio na área de Pedagogia

  Mais notícias: março 2026

In [14]:
#Extraindo links das notícias
#Normalmente os títulos estão dentro de links.
links = soup.find_all("a")

for link in links:
    print(link.get("href"))

http://brasil.gov.br
https://ifpr.edu.br/foz-do-iguacu
https://sei.ifpr.edu.br/sei/modulos/pesquisa/md_pesq_processo_pesquisar.php?acao_externa=protocolo_pesquisar&acao_origem_externa=protocolo_pesquisar&id_orgao_acesso_externo=0
/foz-do-iguacu/
https://foz.ifpr.edu.br/nossos-cursos/
https://ifpr.edu.br/foz-do-iguacu/tecnicos-integrados-3/
https://ifpr.edu.br/foz-do-iguacu/tecnicos-subsequentes/
https://ifpr.edu.br/foz-do-iguacu/superior/
https://ifpr.edu.br/foz-do-iguacu/especializacao-em-ensino-de-ciencias-e-matematica/
https://ifpr.edu.br/foz-do-iguacu/pos-graduacao-lato-sensu-em-internet-das-coisas-iot-do-ifpr/
https://ifpr.edu.br/foz-do-iguacu/qualificacao-profissional-2/
https://ifpr.edu.br/foz-do-iguacu/formacao-inicial-e-continuada/
https://ifpr.edu.br/foz-do-iguacu/curso-de-boas-praticas-de-manipulacao-de-alimentos/
https://ifpr.edu.br/foz-do-iguacu/educacao-a-distancia/
https://ifpr.edu.br/foz-do-iguacu/nossos-campi/
https://ifpr.edu.br/foz-do-iguacu/fale-conosco/
#
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/ifpr/missao-e-valores/
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/ifpr/reitoria/
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/ifpr/website-da-reitoria/
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/ifpr/cpa/
#
https://ifpr.edu.br/foz-do-iguacu/sobre-o-campus/
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/campus/quem-e-quemcampus/
https://ifpr.edu.br/foz-do-iguacu/documentos-institucionais/organograma-do-campus/
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/codic/
#
/servidor/
https://ifpr.edu.br/foz-do-iguacu/servidores/horario-de-trabalho-dos-servidores/
https://calendar.google.com/calendar/embed?src=comunicacao.foz%40ifpr.edu.br&ctz=America%2FSao_Paulo
https://ifpr.edu.br/foz-do-iguacu/ginasio/
https://ifpr.edu.br/foz-do-iguacu/29284-2/
https://ifpr.edu.br/foz-do-iguacu/alunos/calendario-academico/
https://ifpr.edu.br/foz-do-iguacu/processos-seletivos-simplificados/
#
https://planif.ifpr.edu.br/index.planif
https://cope.ifpr.edu.br/
http://200.17.101.6/sispa/
#
https://sites.google.com/view/secretaria-academica/protocolo?authuser=0
https://ifpr.edu.br/foz-do-iguacu/cancelamento-de-registro/
https://ifpr.edu.br/foz-do-iguacu/projeto-politico-pedagogico-ppp/
https://ifpr.edu.br/foz-do-iguacu/ptd/
https://ifpr.edu.br/foz-do-iguacu/livros-didaticos/
/rede-de-bibliotecas-do-ifpr/
#
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/celif/
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/celif/editais/
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/celif/idiomas-sem-fronteiras-isf/
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/celif/my-english-online-meo/
#
https://ifpr.edu.br/foz-do-iguacu/oportunidades/
https://ifpr.edu.br/foz-do-iguacu/alunos/estagios-e-tcc/tec-aquicultura/
https://ifpr.edu.br/foz-do-iguacu/alunos/estagios-e-tcc/tec-cozinha/
https://ifpr.edu.br/foz-do-iguacu/alunos/estagios-e-tcc/tec-informatica/
http://ifpr.edu.br/foz-do-iguacu/serc/
https://ifpr.edu.br/foz-do-iguacu/tecnico-em-meio-ambiente-3/
https://ifpr.edu.br/foz-do-iguacu/gastronomia/
https://ifpr.edu.br/foz-do-iguacu/licenciatura-em-fisica/
#
https://ifpr.edu.br/foz-do-iguacu/editais-2023/
https://ifpr.edu.br/foz-do-iguacu/alunos/bolsas-e-auxilios/assistencia-estudantil-2-2/
https://ifpr.edu.br/foz-do-iguacu/alunos/bolsas-e-auxilios/pesquisa-e-extensao/
https://ifpr.edu.br/foz-do-iguacu/coordenadoria-de-pesquisa-e-extensao/comite-de-pesquisa-e-extensao-cope/
https://ifpr.edu.br/foz-do-iguacu/alunos/informacoes/regulamentos/
https://ifpr.edu.br/foz-do-iguacu/alunos/manuais-e-regulamentacoes/
https://ifpr.edu.br/foz-do-iguacu/certificados-2/
https://ifpr.edu.br/foz-do-iguacu/certificacao-de-conhecimentos-anteriores-2/
https://ifpr.edu.br/menu-academico/egressos/
#
https://ifpr.edu.br/foz-do-iguacu/documentos-institucionais/comunicados-internos-2/
https://ifpr.edu.br/foz-do-iguacu/formularios/
https://ifpr.edu.br/foz-do-iguacu/documentos-institucionais/editais/
https://ifpr.edu.br/foz-do-iguacu/documentos-institucionais/portaria-do-campus/
#
https://ifpr.edu.br/foz-do-iguacu/acesse-o-sei-sistema-eletronico-de-informacoes/
#
https://ifpr.edu.br/foz-do-iguacu/pss-professor-substituto/
https://ifpr.edu.br/foz-do-iguacu/pss-estagiarios/
#
https://ifpr.edu.br/foz-do-iguacu/compras-e-licitacoes/inexigibilidade-de-licitacao/
https://ifpr.edu.br/foz-do-iguacu/compras-e-licitacoes/dispensas-de-licitacao/
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/acesso-a-informacao/2018-2/
https://ifpr.edu.br/foz-do-iguacu/chamamento-publico/
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/acesso-a-informacao/ordem-de-pagamento/
https://ifpr.edu.br/foz-do-iguacu/servico-de-informacao-ao-cidadao/
https://ifpr.edu.br/foz-do-iguacu/menu-institucional/acesso-a-informacao/lei-de-acesso-a-informacao/
https://ifpr.edu.br/foz-do-iguacu/coordenadoria-de-pesquisa-e-extensao/
https://ifpr.edu.br/foz-do-iguacu/coordenadoria-de-pesquisa-e-extensao/comite-de-pesquisa-e-extensao-cope/
https://ifpr.edu.br/foz-do-iguacu/serc/
https://ifpr.edu.br/foz-do-iguacu/napne/
http://revistas.ifpr.edu.br/index.php/index/index
http://editora.ifpr.edu.br/
https://www-periodicos-capes-gov-br.ez109.periodicos.capes.gov.br/
https://ifpr.edu.br/foz-do-iguacu/vagas-de-estagio/
https://ifpr.edu.br/foz-do-iguacu/vagas-de-estagio/
https://ifpr.edu.br/foz-do-iguacu/processos-seletivos-simplificados/
/sistemas
https://ifpr.edu.br/rede-de-bibliotecas-do-ifpr/
/servidor
https://ifpr.edu.br/foz-do-iguacu/tag/extensao/
https://ifpr.edu.br/foz-do-iguacu/projeto-ifpr-maker-ofertara-oficinas-de-programacao-e-robotica-para-estudantes-de-escolas-publicas-4/
https://ifpr.edu.br/foz-do-iguacu/category/noticias/
https://ifpr.edu.br/foz-do-iguacu/ifpr-foz-realiza-programacao-especial-alusiva-ao-mes-das-mulheres/
https://ifpr.edu.br/foz-do-iguacu/tag/esportes/
https://ifpr.edu.br/foz-do-iguacu/jogos-internos-2026-do-ifpr-foz-celebram-o-esporte-e-a-integracao/
https://ifpr.edu.br/foz-do-iguacu/category/noticias/
https://ifpr.edu.br/foz-do-iguacu/cineciencia-promove-reflexao-sobre-o-papel-das-mulheres-na-ciencia-em-evento-especial-no-ifpr/
https://ifpr.edu.br/foz-do-iguacu/tag/internacional/
https://ifpr.edu.br/foz-do-iguacu/ifpr-abre-inscricoes-para-projeto-de-orientacao-a-estudos-no-exterior/
https://ifpr.edu.br/foz-do-iguacu/ifpr-foz-recebe-professor-visitante-da-republica-dominicana/
https://ifpr.edu.br/foz-do-iguacu/publicados-editais-de-afastamento-integral-para-pos-graduacao/
https://ifpr.edu.br/foz-do-iguacu/ifpr-foz-celebra-formatura-2026/
https://ifpr.edu.br/foz-do-iguacu/34030-2/
https://ifpr.edu.br/foz-do-iguacu/abertas-as-inscricoes-para-estagio-na-area-de-pedagogia/
https://ifpr.edu.br/foz-do-iguacu/2026/03/
https://www.youtube.com/conexaoifpr/
/assis-chateaubriand/
/arapongas/
/astorga/
/barracao/
/campo-largo/
/capanema/
/cascavel/
/colombo/
/coronel-vivida/
/curitiba/
/goioere/
/irati/
/ivaipora/
/jacarezinho/
/jaguariaiva/
/londrina/
/palmas/
/paranagua/
/paranavai/
/pinhais/
/pitanga/
/quedas-do-iguacu/
/telemaco-borba/
/umuarama/
/uniao-da-vitoria/
https://ifpr.edu.br/foz-do-iguacu/tecnicos-integrados-2/
https://ifpr.edu.br/foz-do-iguacu/tecnicos-subsequentes/
https://ifpr.edu.br/foz-do-iguacu/curso-de-boas-praticas-de-manipulacao-de-alimentos/
https://ifpr.edu.br/foz-do-iguacu/superior/
https://ifpr.edu.br/foz-do-iguacu/especializacao-em-ensino-de-ciencias-e-matematica/
https://ifpr.edu.br/foz-do-iguacu/pos-graduacao-lato-sensu-em-internet-das-coisas-iot-do-ifpr/
https://ifpr.edu.br/foz-do-iguacu/qualificacao-profissional-2/
https://ifpr.edu.br/foz-do-iguacu/cursos-de-educacao-a-distancia/
https://ifpr.edu.br/foz-do-iguacu/formacao-inicial-e-continuada/
/assis-chateaubriand/
/arapongas/
/astorga/
/barracao/
/campo-largo/
/capanema/
/cascavel/
/colombo/
/coronel-vivida/
/curitiba/
/goioere/
/irati/
/ivaipora/
/jacarezinho/
/jaguariaiva/
/londrina/
/palmas/
/paranagua/
/paranavai/
/pinhais/
/pitanga/
/quedas-do-iguacu/
/telemaco-borba/
/umuarama/
/uniao-da-vitoria/
https://ifpr.edu.br/foz-do-iguacu/fale-conosco/
https://ifpr.edu.br/institucional/orgaos-de-controle/ouvidoria/
https://www.facebook.com/IFPRCampusFoz/
https://www.youtube.com/conexaoifpr/
https://www.instagram.com/ifpr.foz/
https://ifpr.edu.br/politica-de-privacidade/
https://ifpr.edu.br/politica-de-cookies/
https://emec.mec.gov.br/emec/consulta-cadastro/detalhamento/d96957f455f6405d14c6542552b0f6eb/MTQ3MjQ=
https://ifpr.edu.br/foz-do-iguacu/wp-content/uploads/sites/12/2020/02/Ramais-com-atribuicoes.pdf
#topo

In [25]:
conteudo = soup.find("main", id="conteudo")
if conteudo is None:
    print("Conteudo não encontrado")
else :
    noticias = conteudo.find_all("a")

    for noticia in noticias:
        titulo = noticia.text.strip()
        url = noticia.get("href")

        if titulo != None:
            print(titulo, url)

EXTENSÃO https://ifpr.edu.br/foz-do-iguacu/tag/extensao/
Projeto IFPR Maker ofertará oficinas de programação e robótica para estudantes de escolas públicas
O Projeto de Extensão IFPR Maker do Instituto Federal do Paraná – Campus Foz do Iguaçu, coordenado pelo professor Daniel Di Domenico, está com inscrições abertas, até 19 de abril, para oficinas gratuitas e presenciais de formação básica nas áreas de Programação, Robótica Educacional e Cultura Maker. As… https://ifpr.edu.br/foz-do-iguacu/projeto-ifpr-maker-ofertara-oficinas-de-programacao-e-robotica-para-estudantes-de-escolas-publicas-4/
Notícias https://ifpr.edu.br/foz-do-iguacu/category/noticias/
IFPR Foz realiza programação especial alusiva ao Mês das Mulheres
Como você tem contribuído para a igualdade de gênero? Para refletir sobre essa questão tão importante, o Instituto Federal do Paraná… https://ifpr.edu.br/foz-do-iguacu/ifpr-foz-realiza-programacao-especial-alusiva-ao-mes-das-mulheres/
Esportes https://ifpr.edu.br/foz-do-iguacu/tag/esportes/
Jogos Internos 2026 do IFPR Foz celebram o esporte e a integração
Dois dias de muita competição, integração e espírito esportivo marcaram os Jogos Internos do IFPR – Campus Foz do Iguaçu. Realizado… https://ifpr.edu.br/foz-do-iguacu/jogos-internos-2026-do-ifpr-foz-celebram-o-esporte-e-a-integracao/
Notícias https://ifpr.edu.br/foz-do-iguacu/category/noticias/
Cineciência promove reflexão sobre o papel das mulheres na ciência em evento no IFPR Foz
Você já parou para pensar nos desafios enfrentados pelas mulheres que transformaram a história da ciência? Pensando em dar visibilidade a… https://ifpr.edu.br/foz-do-iguacu/cineciencia-promove-reflexao-sobre-o-papel-das-mulheres-na-ciencia-em-evento-especial-no-ifpr/
Internacional https://ifpr.edu.br/foz-do-iguacu/tag/internacional/
IFPR abre inscrições para projeto de orientação a estudos no exterior
O Instituto Federal do Paraná (IFPR) – Campus Foz do Iguaçu está com inscrições abertas para o Projeto de Extensão  “International… https://ifpr.edu.br/foz-do-iguacu/ifpr-abre-inscricoes-para-projeto-de-orientacao-a-estudos-no-exterior/
IFPR Foz recebe professor visitante da República Dominicana https://ifpr.edu.br/foz-do-iguacu/ifpr-foz-recebe-professor-visitante-da-republica-dominicana/
Publicados editais de Afastamento Integral para Pós Graduação https://ifpr.edu.br/foz-do-iguacu/publicados-editais-de-afastamento-integral-para-pos-graduacao/
IFPR Foz celebra Formatura 2026 https://ifpr.edu.br/foz-do-iguacu/ifpr-foz-celebra-formatura-2026/
Divulgado resultado da prova de Suficiência em Inglês – 2026 https://ifpr.edu.br/foz-do-iguacu/34030-2/
Abertas as inscrições para estágio na área de Pedagogia https://ifpr.edu.br/foz-do-iguacu/abertas-as-inscricoes-para-estagio-na-area-de-pedagogia/
março 2026 https://ifpr.edu.br/foz-do-iguacu/2026/03/
Conexão IFPR https://www.youtube.com/conexaoifpr/

In [34]:
dados = []

conteudo = soup.find("main", id="conteudo")
if conteudo is None:
    print("Conteudo não encontrado")
else :
    noticias = conteudo.find_all("a")

    for noticia in noticias:
        titulo_tag = noticia.find("h2", class_="complementares__titulo")
        titulo = titulo_tag.get_text(strip=True) if titulo_tag else ""

        url = noticia.get("href")

        descricao_p = noticia.find("p")
        descricao = descricao_p.get_text(strip=True) if descricao_p else ""

        if titulo != "":
            dados.append({
            "titulo": titulo,
            "descricao" : descricao,
            "link": url
        })

In [35]:
df = pd.DataFrame(dados)

df

,titulo,descricao,link
0,IFPR Foz realiza programação especial alusiva ...,Como você tem contribuído para a igualdade de ...,https://ifpr.edu.br/foz-do-iguacu/ifpr-foz-rea...
1,Jogos Internos 2026 do IFPR Foz celebram o esp...,"Dois dias de muita competição, integração e es...",https://ifpr.edu.br/foz-do-iguacu/jogos-intern...
2,Cineciência promove reflexão sobre o papel das...,Você já parou para pensar nos desafios enfrent...,https://ifpr.edu.br/foz-do-iguacu/cineciencia-...
3,IFPR abre inscrições para projeto de orientaçã...,O Instituto Federal do Paraná (IFPR) – Campus ...,https://ifpr.edu.br/foz-do-iguacu/ifpr-abre-in...

In [36]:
# Salvando os dados
df.to_csv("noticias_ifpr.csv", index=False)

In [37]:
# Extraindo as notícias
import time

def extrair_conteudo(url):
    try:
        time.sleep(1)

        response = requests.get(url)

        if response.status_code != 200:
            return ""

        soup = BeautifulSoup(response.text, "html.parser")

        # h1 (título da notícia)
        h1 = soup.find("h1")
        titulo = h1.get_text(strip=True) if h1 else ""

        # conteúdo (parágrafos)
        paragrafos = soup.find_all("p")

        texto = " ".join([p.get_text(strip=True) for p in paragrafos])

        return f"{titulo} {texto}"

    except Exception as e:
        print(f"Erro em {url}: {e}")
        return ""

In [38]:
# Criando a coluna conteudo e extraindo dados das páginas.
df["conteudo"] = df["link"].apply(extrair_conteudo)

In [39]:
df

,titulo,descricao,link,conteudo
0,IFPR Foz realiza programação especial alusiva ...,Como você tem contribuído para a igualdade de ...,https://ifpr.edu.br/foz-do-iguacu/ifpr-foz-rea...,IFPR Foz realiza programação especial alusiva ...
1,Jogos Internos 2026 do IFPR Foz celebram o esp...,"Dois dias de muita competição, integração e es...",https://ifpr.edu.br/foz-do-iguacu/jogos-intern...,Jogos Internos 2026 do IFPR Foz celebram o esp...
2,Cineciência promove reflexão sobre o papel das...,Você já parou para pensar nos desafios enfrent...,https://ifpr.edu.br/foz-do-iguacu/cineciencia-...,Cineciência promove reflexão sobre o papel das...
3,IFPR abre inscrições para projeto de orientaçã...,O Instituto Federal do Paraná (IFPR) – Campus ...,https://ifpr.edu.br/foz-do-iguacu/ifpr-abre-in...,IFPR abre inscrições para projeto de orientaçã...

In [42]:
# Outra maneira de fazer
# cria a coluna vazia antes (boa prática)
df["conteudo"] = ""
for index, row in df.iterrows():

    url = row["link"]
    # atualiza o dataframe
    df.at[index, "conteudo"] = extrair_conteudo(url) # Mais direto
    #df.loc[index, "conteudo"] = extrair_conteudo(url) # Mais pesado
df

,titulo,descricao,link,conteudo
0,IFPR Foz realiza programação especial alusiva ...,Como você tem contribuído para a igualdade de ...,https://ifpr.edu.br/foz-do-iguacu/ifpr-foz-rea...,IFPR Foz realiza programação especial alusiva ...
1,Jogos Internos 2026 do IFPR Foz celebram o esp...,"Dois dias de muita competição, integração e es...",https://ifpr.edu.br/foz-do-iguacu/jogos-intern...,Jogos Internos 2026 do IFPR Foz celebram o esp...
2,Cineciência promove reflexão sobre o papel das...,Você já parou para pensar nos desafios enfrent...,https://ifpr.edu.br/foz-do-iguacu/cineciencia-...,Cineciência promove reflexão sobre o papel das...
3,IFPR abre inscrições para projeto de orientaçã...,O Instituto Federal do Paraná (IFPR) – Campus ...,https://ifpr.edu.br/foz-do-iguacu/ifpr-abre-in...,IFPR abre inscrições para projeto de orientaçã...

In [43]:
# Salvando os dados
df.to_csv("noticias_ifpr.csv", index=False)

In [44]:
import requests
from bs4 import BeautifulSoup

url = "https://www.ifpr.edu.br/sitemap.xml"

response = requests.get(url)

soup = BeautifulSoup(response.text, "xml")

urls = [loc.text for loc in soup.find_all("loc")]

print(urls[:10])

['https://ifpr.edu.br/wp-sitemap-posts-post-1.xml', 'https://ifpr.edu.br/wp-sitemap-posts-post-2.xml', 'https://ifpr.edu.br/wp-sitemap-posts-post-3.xml', 'https://ifpr.edu.br/wp-sitemap-posts-post-4.xml', 'https://ifpr.edu.br/wp-sitemap-posts-page-1.xml', 'https://ifpr.edu.br/wp-sitemap-posts-page-2.xml', 'https://ifpr.edu.br/wp-sitemap-posts-page-3.xml', 'https://ifpr.edu.br/wp-sitemap-posts-anexo-documento-1.xml', 'https://ifpr.edu.br/wp-sitemap-posts-doc-institucional-1.xml', 'https://ifpr.edu.br/wp-sitemap-posts-epkb_post_type_1-1.xml']